# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  ImGui_config = debug
  GLAD_config = debug
  freetype_config = debug
  msdfgen_config = debug
  msdf_atlas_gen_config = debug
  Box2D_config = debug
  OptickCore_config = debug
  yaml_cpp_config = debug
  TerranEngine_config = debug
  TerranScriptCore_config = debug
  TerranEditor_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  ImGui_config = release
  GLAD_config = release
  freetype_config = release
  msdfgen_config = release
  msdf_atlas_gen_config = release
  Box2D_config = release
  OptickCore_config = release
  yaml_cpp_config = release
  TerranEngine_config = release
  TerranScriptCore_config = release
  TerranEditor_config = release
  Sandbox_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW ImGui GLAD freetype msdfgen msdf-atlas-gen Box2D OptickCore yaml-cpp TerranEngine TerranScriptCore TerranEditor Sandbox

.PHONY: all clean help $(PROJECTS) Core Dependencies Runtime Tools

all: $(PROJECTS)

Core: TerranEngine TerranScriptCore

Dependencies: Box2D GLAD GLFW ImGui OptickCore freetype msdf-atlas-gen msdfgen yaml-cpp

Runtime: Sandbox

Tools: TerranEditor

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C TerranEngine/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C TerranEngine/vendor/ImGui -f Makefile config=$(ImGui_config)
endif

GLAD:
ifneq (,$(GLAD_config))
	@echo "==== Building GLAD ($(GLAD_config)) ===="
	@${MAKE} --no-print-directory -C TerranEngine/vendor/GLAD -f Makefile config=$(GLAD_config)
endif

freetype:
ifneq (,$(freetype_config))
	@echo "==== Building freetype ($(freetype_config)) ===="
	@${MAKE} --no-print-directory -C TerranEngine/vendor/msdf-atlas-gen/msdfgen/freetype -f Makefile config=$(freetype_config)
endif

msdfgen: freetype
ifneq (,$(msdfgen_config))
	@echo "==== Building msdfgen ($(msdfgen_config)) ===="
	@${MAKE} --no-print-directory -C TerranEngine/vendor/msdf-atlas-gen/msdfgen -f Makefile config=$(msdfgen_config)
endif

msdf-atlas-gen: msdfgen
ifneq (,$(msdf_atlas_gen_config))
	@echo "==== Building msdf-atlas-gen ($(msdf_atlas_gen_config)) ===="
	@${MAKE} --no-print-directory -C TerranEngine/vendor/msdf-atlas-gen -f Makefile config=$(msdf_atlas_gen_config)
endif

Box2D:
ifneq (,$(Box2D_config))
	@echo "==== Building Box2D ($(Box2D_config)) ===="
	@${MAKE} --no-print-directory -C TerranEngine/vendor/Box2D -f Makefile config=$(Box2D_config)
endif

OptickCore:
ifneq (,$(OptickCore_config))
	@echo "==== Building OptickCore ($(OptickCore_config)) ===="
	@${MAKE} --no-print-directory -C TerranEngine/vendor/Optick -f Makefile config=$(OptickCore_config)
endif

yaml-cpp:
ifneq (,$(yaml_cpp_config))
	@echo "==== Building yaml-cpp ($(yaml_cpp_config)) ===="
	@${MAKE} --no-print-directory -C TerranEngine/vendor/yaml-cpp -f Makefile config=$(yaml_cpp_config)
endif

TerranEngine: GLFW ImGui GLAD msdf-atlas-gen Box2D OptickCore yaml-cpp
ifneq (,$(TerranEngine_config))
	@echo "==== Building TerranEngine ($(TerranEngine_config)) ===="
	@${MAKE} --no-print-directory -C TerranEngine -f Makefile config=$(TerranEngine_config)
endif

TerranScriptCore:
ifneq (,$(TerranScriptCore_config))
	@echo "==== Building TerranScriptCore ($(TerranScriptCore_config)) ===="
	@${MAKE} --no-print-directory -C TerranScriptCore -f Makefile config=$(TerranScriptCore_config)
endif

TerranEditor: TerranEngine
ifneq (,$(TerranEditor_config))
	@echo "==== Building TerranEditor ($(TerranEditor_config)) ===="
	@${MAKE} --no-print-directory -C TerranEditor -f Makefile config=$(TerranEditor_config)
endif

Sandbox: TerranEngine
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C TerranEngine/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C TerranEngine/vendor/ImGui -f Makefile clean
	@${MAKE} --no-print-directory -C TerranEngine/vendor/GLAD -f Makefile clean
	@${MAKE} --no-print-directory -C TerranEngine/vendor/msdf-atlas-gen/msdfgen/freetype -f Makefile clean
	@${MAKE} --no-print-directory -C TerranEngine/vendor/msdf-atlas-gen/msdfgen -f Makefile clean
	@${MAKE} --no-print-directory -C TerranEngine/vendor/msdf-atlas-gen -f Makefile clean
	@${MAKE} --no-print-directory -C TerranEngine/vendor/Box2D -f Makefile clean
	@${MAKE} --no-print-directory -C TerranEngine/vendor/Optick -f Makefile clean
	@${MAKE} --no-print-directory -C TerranEngine/vendor/yaml-cpp -f Makefile clean
	@${MAKE} --no-print-directory -C TerranEngine -f Makefile clean
	@${MAKE} --no-print-directory -C TerranScriptCore -f Makefile clean
	@${MAKE} --no-print-directory -C TerranEditor -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   ImGui"
	@echo "   GLAD"
	@echo "   freetype"
	@echo "   msdfgen"
	@echo "   msdf-atlas-gen"
	@echo "   Box2D"
	@echo "   OptickCore"
	@echo "   yaml-cpp"
	@echo "   TerranEngine"
	@echo "   TerranScriptCore"
	@echo "   TerranEditor"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"