# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

ifeq ($(config),debug)
  CSC = csc
  RESGEN = resgen
TARGETDIR = ScriptAssemblies
TARGET = $(TARGETDIR)/ScriptAssembly.dll
OBJDIR = ScriptAssemblies/Intermidiates/Debug
  FLAGS = /debug /noconfig /d:TR_DEBUG
  DEPENDS =
  REFERENCES = 
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef
endif

ifeq ($(config),release)
  CSC = csc
  RESGEN = resgen
TARGETDIR = ScriptAssemblies
TARGET = $(TARGETDIR)/ScriptAssembly.dll
OBJDIR = ScriptAssemblies/Intermidiates/Release
  FLAGS = /optimize /noconfig /d:TR_RELEASE
  DEPENDS =
  REFERENCES = 
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef
endif

FLAGS += /t:library 
REFERENCES += /r:../Resources/Scripts/TerranScriptCore.dll

SOURCES += \
	Assets/Scripts/Pong/Ball.cs \
	Assets/Scripts/Pong/CollisionUtils.cs \
	Assets/Scripts/Pong/GameManager.cs \
	Assets/Scripts/Pong/Player.cs \
	Assets/Scripts/Pong/Test.cs \

EMBEDFILES += \

RESPONSE += $(OBJDIR)/ScriptAssembly.rsp
SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

all: prebuild $(EMBEDFILES) $(COPYFILES) $(TARGET)

$(TARGET): $(SOURCES) $(EMBEDFILES) $(DEPENDS) $(RESPONSE) | $(TARGETDIR)
	$(PRELINKCMDS)
	$(SILENT) $(CSC) /nologo /out:$@ $(FLAGS) $(REFERENCES) @$(RESPONSE) $(patsubst %,/resource:%,$(EMBEDFILES))
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(RESPONSE): ScriptAssembly.make
	@echo Generating response file
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f $(RESPONSE)
else
	$(SILENT) if exist $(RESPONSE) del $(OBJDIR)\ScriptAssembly.rsp
endif
	@echo Assets/Scripts/Pong/Ball.cs >> $(RESPONSE)
	@echo Assets/Scripts/Pong/CollisionUtils.cs >> $(RESPONSE)
	@echo Assets/Scripts/Pong/GameManager.cs >> $(RESPONSE)
	@echo Assets/Scripts/Pong/Player.cs >> $(RESPONSE)
	@echo Assets/Scripts/Pong/Test.cs >> $(RESPONSE)

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)
